# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_list',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('auction_id', models.IntegerField(default=0)),
                ('suggest_price', models.IntegerField(default=0)),
                ('suggest_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
