# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_list',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('edition', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='item_information',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('reserved_price', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('book_number', models.IntegerField(default=0)),
                ('on_going', models.BooleanField(default=False)),
            ],
        ),
    ]
