# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_information',
            old_name='book_number',
            new_name='edition',
        ),
        migrations.AddField(
            model_name='book_list',
            name='department',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_information',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_information',
            name='book_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
