# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 07:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auction_list',
            fields=[
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField(choices=[(datetime.datetime(2016, 6, 7, 16, 35, 31, 584864), '1 days'), (datetime.datetime(2016, 6, 9, 16, 35, 31, 584864), '3 days'), (datetime.datetime(2016, 6, 11, 16, 35, 31, 584864), '5 days'), (datetime.datetime(2016, 6, 13, 16, 35, 31, 584864), '7 days')])),
                ('current_price', models.IntegerField(default=0)),
                ('book_id', models.IntegerField(default=0)),
                ('bidding_state', models.BooleanField(default=True)),
                ('expected_winner', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='success_auction',
            fields=[
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('winner_id', models.IntegerField(default=0)),
            ],
        ),
    ]
