# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_list',
            name='book_id',
        ),
        migrations.AddField(
            model_name='auction_list',
            name='book_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction_list',
            name='due_date',
            field=models.DateTimeField(choices=[(datetime.datetime(2016, 6, 8, 7, 57, 56, 646487), '1 days'), (datetime.datetime(2016, 6, 10, 7, 57, 56, 646487), '3 days'), (datetime.datetime(2016, 6, 12, 7, 57, 56, 646487), '5 days'), (datetime.datetime(2016, 6, 14, 7, 57, 56, 646487), '7 days')]),
        ),
    ]
